version: "3.8"
services:
  mysql:
    platform: linux/x86_64
    image: "guestbook-mysql"
    build:
      context: ./
      dockerfile: ./docker/mysql.dockerfile
    volumes:
      - /var/lib/mysql
    env_file:
      - ./env/.env
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 5s
      timeout: 1s
      retries: 5
      start_period: 0s
