version: "3.8"
services:
  mysql:
    platform: linux/x86_64
    image: "guestbook-mysql"
    build:
      context: ./
      dockerfile: ./docker/mysql.dockerfile
    volumes:
      - /var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - ./.env
