version: "3.8"
services:
  api:
    build:
      context: ./
      dockerfile: ./docker/node.dockerfile
    environment:
      - NODE_ENV=stage
    env_file:
      - ./env/.env
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    platform: linux/x86_64
    image: "guestbook-mysql"
    build:
      context: ./
      dockerfile: ./docker/mysql.dockerfile
    volumes:
      - /var/lib/mysql
    env_file:
      - ./env/.env
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 5s
      timeout: 1s
      retries: 5
      start_period: 0s
